README.md
header.go
header_test.go
protocol.go
protocol_test.go
v1.go
v2.go

This is an attempt to partially address #3 with pieces of #2. The reason why I'm not merging #2 ~(or the code I have here)~ is because I don't feel confident enough it isn't introducing breaking changes to any existing users of this library who may be pulling from master branch.
@Freeaqingme @mgouline @elico @anisse can you PTAL?
**TODO**

api: introduce net.Listener and net.Conn wrappers

---

protocol.go
v2.go
v2_test.go

When receiving proxy v2 headers with the command field set to zero (i.e. LOCAL commands) the rest of the header should be skipped over until length.
From the spec:
> \x0 : LOCAL : the connection was established on purpose by the proxy without being relayed. The connection endpoints are the sender and the receiver. Such connections exist when the proxy sends health-checks to the server. The receiver must accept this connection as valid and must use the real connection endpoints and discard the protocol block including the family which is ignored.
and later in the spec:
> When a sender presents a LOCAL connection, it should not present any address so it sets this field to zero. Receivers MUST always consider this field to skip the appropriate number of bytes and must not assume zero is …

proxyv2 LOCAL commands still need to skip over dummy header fields.

---

header.go
policy.go
policy_test.go
protocol.go
protocol_test.go

This introduces the possibility to decide on each new incoming connection whether the proxy header should be used, ignored, or the connection be rejected. It also allows to reject the connection when a proxy header is required but not send at all.
Without such a possibility usage of this library is prone to security attacks enabling simple faking of client IP addresses by accepting any proxy protocol header regardless of whether the upstream source is allowed to send one or not. The need for this is derived from our use case, where we have an application which accepts connections both through a proxy and direct (there's a reason for that). If we would allow the proxy header for direct connections it would allow clients to pretend they are from another IP address which we don't want.
While …

Add possibility to handle proxy info differently depending on upstream IP

---

protocol.go

If the `ProxyHeaderPolicy` is set to `REQUIRE` the header is enforced but not used. This pr proposes to change this behavior to not only enforce the presence of the proxy protocol header but also using it if the policy is set to `REQUIRE`.

Use protocol header if policy is set to REQUIRE

---

tlvparse/azure.go
tlvparse/azure_test.go

@pires do you accept contributions to tlvparse extension package? If so I'd like to add Azure support, which is fairly similar to AWS.
The support is modeled on `aws.go` under `tlvparse`. The Azure spec is similar but
encodes `uint32` instead of a string. Because of that I've opted for an
additional boolean indicating if given value was found -- the zero value of
`uint32` is technically a valid header value.
Let me know what do you think.
BTW We currently have a similar implementation (diff func names, etc. but the logic is the same) in our codebase but we don't run it in production yet. I've tested it on a dev env with Azure Private Link set up, and the header is parsed correctly.
---
Azure spec: https://docs.microsoft.com/en-us/azure/private-link/private-link-service-overview#getting-con …

Add support for Azure extensions

---

header.go
header_test.go

The current behaviour of `Read` is to discard the underlying error and return `ErrNoProxyProtocol`. That makes it tricky to debug what is wrong.
In my case, I was trying to nest `tls.NewListener` inside a `proxyproto.Listener` but got the ordering wrong, the underlying error was:
```
tls: first record does not look like a TLS handshake
```
This patch surfaces that error to the caller.
Note: It may be a good idea to do the same thing with the other `.Peek()` calls too.

header: return err from reader.Peek()

---

protocol_test.go

This is an integration test that reproduces a TLS server getting a non-TLS message.
Before https://github.com/pires/go-proxyproto/pull/21, this would return a non-descript `Proxy protocol signature not present` message.
With that patch, we now surface the underlying error, in this case `tls: first record does not look like a TLS handshake`.
It's quite verbose, mostly because the TLS stuff requires a lot of setup.
refs https://github.com/pires/go-proxyproto/issues/3

integration test for misconfigured TLS server

---

header.go
policy.go
tlv.go
v2.go

This makes it easier to track down where errors come from.

Prefix error messages with package name

---

v1.go
v1_test.go

These are internal V1 details, users of this package shouldn't need
them.
Closes: https://github.com/pires/go-proxyproto/issues/29

Stop exporting CRLF and SEPARATOR

---

README.md
header.go

go-proxyproto implements features that appeared in newer revisions of
the spec. Link the latest one.
While at it, convert links to HTTPS.

Update spec URL

---

header_test.go
tlv.go
tlv_test.go
tlvparse/aws.go
tlvparse/azure.go
tlvparse/azure_test.go
tlvparse/ssl.go
tlvparse/ssl_test.go

len(tlv.Value) can be used instead, and reduces the chances of a
mismatch between the actual length and the user-supplied Length field
when the user generates TLVs.
Obviously, this is a breaking change.
Closes: https://github.com/pires/go-proxyproto/issues/35

Nuke TLV.Length

---

protocol.go
protocol_test.go

this blocks implementing the listener in traefik
https://github.com/traefik/traefik/pull/7320
If you accept it, please create a new version tag, thank you!
closes #50

exporting underlying Connection

---

protocol.go
protocol_test.go

This function returns the full proxy protocol header, if available.
Sometimes the local/remote addresses aren't enough and the caller is
interested in e.g. TLVs.

Add Conn.ProxyHeader

---

tlvparse/ssl.go

In case the client didn't present a certificate, then there's no CN TLV that
could be populated by the proxy.
haproxy also omits this field in this case. The TLV is only appended if
ssl_sock_get_remote_common_name returns a positive integer [1]. The
function returns 0 in case the CN isn't found [2].
[1]: https://github.com/haproxy/haproxy/blob/233ad288cd4b855ba5fd08342433a0f5d20e625d/src/connection.c#L1510
[2]: https://github.com/haproxy/haproxy/blob/4299528390ce197a06c0ef1d59a4696fa9c19c30/src/ssl_sock.c#L6092

Don't make SSL_CN mandatory

---

protocol.go
protocol_test.go

After the type-specific underlying connection getters were introduced in #51 There's still use for a generic getter.
For example: there might be more wrappers to the connection, and if all wrappers could implement the `Conn() net.Conn` interface, a trivial resolver could unwrap them all and get to the actual-underlying connection in a generic way.

Add Generic Underlying Connection Getter

---

tlv.go
tlv_test.go

We hit this issue when reading a 0 byte custom TLV value. Testing identified that this was because the length was 0 bytes and the length check in this PR was affecting it.

Fixed incorrect truncated tlv error that prevents reading empty (0 byte) TLVs

---

addr_proto.go
header.go
protocol.go
v1.go
v1_test.go
v2.go
v2_test.go

Fixes #60
I took the opportunity to improve test debuggability for v1 and v2 code.
Warning: changes to v1 errror handling may break someone's code but should be trivial to address. I'm taking this breaking change lightly because of that and because this is still a 0.x release, which should clearly communicate the API is not stable.

Support v1 UNKNOWN and v2 UNSPEC when command is LOCAL

---

v2.go
v2_test.go

Fixes https://github.com/pires/go-proxyproto/pull/61#issuecomment-762556537

v2: read length and skip the bytes for UNSPEC

---

header.go
header_test.go
v1.go
v1_test.go
v2.go
version_cmd.go

The changes in #61 overrides all `header.Command` to `LOCAL` (which was set to `PROXY` by `initVersion1`) unconditionally.
https://github.com/pires/go-proxyproto/blob/b6f440c01c68bf65792f463adcc71eb620fb0484/v1.go#L55-L60
This makes these functions returning the original addresses rather than the addresses contained in the proxy header.
https://github.com/pires/go-proxyproto/blob/b6f440c01c68bf65792f463adcc71eb620fb0484/protocol.go#L127-L155
Unfortunately, the problem was not revealed, since the `EqualsTo` function, which is used by the tests to compare actual and expected headers, straightly returns true when the command is LOCAL, and the command is not being compared.
https://github.com/pires/go-proxyproto/blob/b6f440c01c68bf65792f463adcc71eb620fb0484/header.go#L150-L170
This PR also …

v1: fix command always LOCAL

---

header.go
header_test.go
v1.go
v1_test.go

2As suggested in PR#70, a new pull request which captures just the tests proving issue #69, with some refinements:
- header overflow (i.e. reads more than the bufio.Reader default buffer size of 4096).
- "slow loris" type vulnerability, where the header read blocks waiting for terminator.
The second issue above can be used for DoS by consuming server process sockets.
Will then submit fixes - further testing shows that pull request #70 does not solve the problem properly.
Fixes #69

tests and fixes for issue #69

---

README.md
examples/client/client.go
examples/httpserver/httpserver.go
examples/server/server.go
protocol.go
protocol_test.go

Set a read deadline when waiting for the PROXY protocol header.

Add support for ReadHeaderTimeout

---

tlvparse/gcp.go
tlvparse/gcp_test.go

```
The support is modeled on azure.go under tlvparse. The GCP spec is similar but
encodes uint64. There's no subtype. Since zero value of uint64 is technically
a valid header value, I've opted for an extra boolean to indicate if it was
found (same as with Azure).
```
Given that we already have AWS, and Azure in `tlvparse` I thought it will be a good idea to add the GCP support as well.
We use it with GCP in our pre-prod env and all seems to be working well.
Let me know if you think it makes sense to have this with the upstream lib.

Add support for GCP extensions

---

.github/workflows/test.yml
protocol.go
protocol_test.go
tlv_test.go

Can you, please, help review @unmarshal, as it is related to your PR #74?
Fixes #75

Reset read deadline after parsing header

---

.github/workflows/test.yml
protocol.go

Fixed the race by using atomic.Value instead of unprotected time.Time 
It was nessasarry to restructure the Conn struct because of this:
```struct of size 80 could be 72 (fieldalignment)```

protocol: fixed deadline datarace #86

---

protocol.go
protocol_test.go

When dealing with slow networks and TLS, 200ms is often hit. Bump
the default timeout to 10s, which is what crupto/tls uses for the
TLS handshake.
Closes: https://github.com/pires/go-proxyproto/issues/83

Bump DefaultReadHeaderTimeout to 10s

---

tlvparse/ssl.go
tlvparse/ssl_test.go

Tests are using a header captured from haproxy with "proxy-v2-options
ssl-cipher" set.
To use this with haproxy you also need to set the ssl-cipher option,
something like:
backend test
default-server send-proxy-v2-ssl proxy-v2-options ssl-cipher
server a [::1]:8080

Add method to get SSL cipher from the SSL TLV

---

policy.go
policy_test.go
protocol.go
protocol_test.go

Add SKIP policy to not expect a PROXY header

---

.github/workflows/golangci-lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
protocol.go
protocol_test.go
tlvparse/ssl.go
v1_test.go

This PR revisits our CI and introduces code linting and automatic releases.
Fixes #58 
Fixes #98

Revisit CI

---

examples/httpserver/httpserver.go
go.mod
go.sum
helper/http2/http2.go
helper/http2/http2_test.go
helper/http2/listener.go

The standard library's http.Server supports HTTP/2, but only for tls.Conn. This doesn't work when serving connections behind a reverse proxy which terminates TLS and uses the PROXY protocol.
Supporting this requires some glue code, which the new helper provides.
The example was tested with tlstunnel.
Closes: https://github.com/pires/go-proxyproto/issues/90

Add an helper for proxied HTTP/2

---

protocol.go

add SetReadHeaderTimeout opt for NewConn

add SetReadHeaderTimeout opt for NewConn

---

header.go

If header.Version != otherHeader.Version then otherHeader.rawTLVs is not present.
This resulted in a crash at my side.  Switching position of the 2 ifs solves it.

header.go prevent otherHeader.rawTLVs being nil

---

protocol.go
protocol_test.go

Use smaller buffer size, and use buffer only to read the PROXY header.
Users may use they own buffers with they own buffer sizes and pools - connection should respect that.

protocol: avoid double buffering

---

protocol.go
protocol_test.go

This PR is designed to prevent listeners being stopped when an error is returned, if the upstream connection address is not trusted (`ErrInvalidUpstream`). Instead, we continue to close the connection but now the `Accept` method has a `for` loop to continue looking for other connections to accept.
In using this library we discovered that the listener `Accept` method returning an error caused the listener to be closed and never reopened when trying to serve HTTP endpoints.
The change was based on [github.com/armon/go-proxyproto/](https://github.com/armon/go-proxyproto/blob/master/protocol.go#L70) which does something similar with the loop and checking for a particular type of error.
Notes: 
See: [`net/http/server.go => Serve(l net.Listener)`](https://cs.opensource.google/go/go/+/master:src/ …

Protocol: Keep listener listening if we don't trust the upstream address

---

protocol.go
protocol_test.go

With commit 7f1f93d the default timeout was changed from 200ms to 10s however the Go Documentation still shows the old default.
This commit fixes that, also I clarified in the protocol_test.go why the DefaultReadHeader is changed to 200ms.
No extra tests are needed since there is no Go code added, changed or removed.

Fix Go Documentation of Default timeout
